jobs:
  kics-job:
   runs-on: ubuntu:latest
   permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
   name: kics-action
   steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir

      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v2.1.0
        with:
          path: "./terraform"
          ignore_on_exit: results
          output_path: results-dir
          platform_type: terraform
          output_formats: "json,sarif"
          exclude_paths: "terraform/gcp/big_data.tf,terraform/azure"
          # seek query id in it's metadata.json
          exclude_queries: 0437633b-daa6-4bbc-8526-c0d2443b946e

      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif

