name: Test KICS action PR comment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:
  kics-job:
   runs-on: ubuntu-latest
   permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      pull-requests: write
   name: kics-action
   steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir

      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v2.1.0
        with:
          path: "./terraform"
          ignore_on_exit: results
          output_path: results-dir
          #platform_type: terraform
          #output_formats: "json,sarif"
          token: "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"
          #exclude_paths: "terraform/gcp/big_data.tf,terraform/azure"
          # seek query id in it's metadata.json
          #exclude_queries: 0437633b-daa6-4bbc-8526-c0d2443b946e
          enable_comments: true

      - name: Show results
        run: |
          cat results-dir/results.sarif
          # cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif
      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kics-sarif-report
          path: results-dir/results.sarif

