
name: terraform plan

on: push
  # inputs:
  #  environment:
  #    description: 'The environment to deploy to (e.g., prod, nonprod)'
  #    required: true

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "< 1.6.0"
         
      - name: Terraform format
        id: fmt
        run: terraform fmt -diff -check -recursive -no-color

      - name: terraform init
        id: init
        run: terraform init -backend=false
    
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Status
        if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure'
        run: exit 1
       
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

        
      
         
 
